/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.codesoom.demo;

import com.sun.net.httpserver.HttpHandler;
import com.sun.net.httpserver.HttpServer;

import java.io.IOException;
import java.net.InetSocketAddress;

public class App {
    public String getGreeting() {
        return "Hello, World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());

        // 익셉션을 내기 때문에, try catch로 예외처리
        try {
            InetSocketAddress address  = new InetSocketAddress(8000); // option + click : 메서드의 구조를 볼 수 있음. localhost는 생략 가능
            HttpServer httpServer = HttpServer.create(address, 0);

            HttpHandler handler = new DemoHttpHandler();
            httpServer.createContext("/", handler);

            httpServer.start(); // 서버 띄워주기
        } catch (IOException e) {
            e.printStackTrace();
        }

    }
}
