/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.assignment1.demo;

import com.sun.net.httpserver.HttpHandler;
import com.sun.net.httpserver.HttpServer;

import java.io.IOException;
import java.net.InetSocketAddress;

public class App {
    public String getGreeting() {
        return "Hello, world!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());


        try {
            final String LOCAL_HOST = "localhost";
            final int PORT = 8000;
            InetSocketAddress address = new InetSocketAddress(LOCAL_HOST, PORT);
            HttpServer httpServer = HttpServer.create(address, 0);
            // 404, 500 error를 방지하기 위한 로직
            HttpHandler handler = new DemoHttpHandler();
            httpServer.createContext("/", handler);
            // 서버 시작
            httpServer.start();
        } catch (IOException e) {
            e.printStackTrace();
        }
    }
}
